### ISSUE TITLE
Create an endpoint that allows to load all places to the map

### ISSUE THREAD

**Issue by boy4uck** [bobocode-labs/gojohnny-rest-api#13]
Create new `GET` endpoint using url `.../places/bounds`. It should receive four mandatory parameters:
* `minLat`
* `minLng`
* `maxLat`
* `maxLng`

The response should be a **list of places** following [GeoJSON](http://geojson.org/) standard.

**Comment by boy4uck** [comment]
@svlugovoy check out the following **PostGIS functions**:
* [st_contains](https://postgis.net/docs/ST_Contains.html)
* [st_x](https://postgis.net/docs/ST_X.html)
* [st_y](https://postgis.net/docs/ST_Y.html)

**Comment by svlugovoy** [comment]
Some test data:
	INSERT INTO place values (10, 'Name1', 1500, 'POINT(-126.4 45.32)');
	INSERT INTO place values (11, 'Name2', 1520, 'POINT(-125.4 47.32)');
	INSERT INTO place values (12, 'Name3', 1750, 'POINT(-126.4 46.32)');

**Comment by boy4uck** [comment]
@svlugovoy, are you sure that these SQL queries are valid?

**Comment by svlugovoy** [comment]
yep, checked right now)

**Comment by svlugovoy** [comment]
This will request for test - return 1 place (id=12) (see test data bellow - 3 places)
http://localhost:8080/places/search/bounds?minLat=46.1&minLng=-126.6&maxLat=46.5&maxLng=-126.4
