### ISSUE TITLE
Extend Place entity with photo URL

### ISSUE THREAD

**Issue by boy4uck** [bobocode-labs/gojohnny-rest-api#21]
In class `Place` create new `String`  field named `photoUrl`. This field should be optional. **All database schema changes should done using migration scripts.**

**Comment by omgkanamikun** [comment]
After changin model & creating migration script I cant run application because postgres reject connection
Error  trace:
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"

**Comment by omgkanamikun** [comment]
to install postgis extention POSTGIS you need use Stack Builder

**Comment by svlugovoy** [comment]
Added comment, created new ticket in backlog (db name convention)
https://github.com/bobocode-labs/gojohnny-rest-api/pull/26/files
