### ISSUE TITLE
Add to README file how to run application locally without changing application.yml

### ISSUE THREAD

**Issue by boy4uck** [bobocode-labs/gojohnny-rest-api#24]
Investigate possible ways to run *Spring Boot* app locally (having active profile `dev`) without changing the `application.yml`.

Check Spring docs [Set the Active Spring Profiles](https://docs.spring.io/spring-boot/docs/2.0.5.RELEASE/reference/htmlsingle/#howto-set-active-spring-profiles), and add corresponding hints to the README file.

**Comment by omgkanamikun** [comment]
added requested solution to README file
