### ISSUE TITLE
Create new Photo entity

### ISSUE THREAD

**Issue by boy4uck** [bobocode-labs/gojohnny-rest-api#49]
Create new `Photo` entity with the following mandatory fields:
* `id` - auto generated
* `url` - a valid URL where photo is located
* `creationTime` 
* `author` - a reference to `User` that posted a photo

Add corresponding **JPA repository** and the **migration script.**

**Comment by govi20** [comment]
would like to work on it. Can you please assign me it. If you are open for contribution.
